# Site settings
title: COVID-19 response tracker
description: Tracking university responses to COVID-19.
baseurl: "/covid19" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: COVID-19 response tracker
user_description: This group seeks to explore alternate futures for academic institutions at a time of precarity and transformation. The present project addresses the impact of the COVID-19 outbreak on labor and safety. We are currently gathering data on nation-wide return to campus plans for fall 2020.
user_title: Visionary Futures Collective
email: visionaryfuturescollective@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
